In [7]:
import geopandas as gpd
from simpledbf import Dbf5
from osgeo import gdal

import pandas as pd

from PIL import Image
import tifffile

import matplotlib.pyplot as plt

from shapely.geometry import Polygon

import folium

In [23]:
# SHP file
# SAMPLE
#shapefile = gpd.read_file("izium_building_damage_data_sample.shp") 

# FULL
shapefile = gpd.read_file("building_damage_data_eastern_cooridor.shp")


# DBF file. Contains all columns of .shp file except geometry
dbf = Dbf5('building_damage_data_eastern_cooridor.dbf')
polygons_without_geometry = dbf.to_dataframe()

# .fix file is not relevant

def damage_area_to_broken_windows(damage_area):
    """ 
    TODO: map damage area to broken windows using
     reasonable assumptions.
    """
    return damage_area**(1/2)

In [9]:
shapefile

,area,FID,damage,geoType,geometry
0,424.100509,762702,0,Polygon,"POLYGON ((33.39421 46.83535, 33.39466 46.83542..."
1,101.200486,759121,0,Polygon,"POLYGON ((33.41580 46.83992, 33.41587 46.83993..."
2,36.328844,160600,0,Polygon,"POLYGON ((33.42569 46.84246, 33.42576 46.84249..."
3,120.023081,840027,0,Polygon,"POLYGON ((33.35309 46.80036, 33.35320 46.80042..."
4,27.361269,387955,0,Polygon,"POLYGON ((33.42683 46.84238, 33.42688 46.84239..."
...,...,...,...,...,...
922820,86.413986,523519,0,Polygon,"POLYGON ((31.49095 52.09397, 31.49109 52.09406..."
922821,19.730201,851199,0,Polygon,"POLYGON ((34.12567 51.69422, 34.12571 51.69425..."
922822,27.102379,458239,0,Polygon,"POLYGON ((33.92598 51.68630, 33.92604 51.68633..."
922823,74.472819,261887,0,Polygon,"POLYGON ((33.52908 52.24539, 33.52921 52.24539..."
922824,30.037356,458751,0,Polygon,"POLYGON ((31.58324 52.02192, 31.58324 52.02196..."

In [10]:
polygons_without_geometry

              area     FID  damage  geoType
0       424.100509  762702       0  Polygon
1       101.200486  759121       0  Polygon
2        36.328844  160600       0  Polygon
3       120.023081  840027       0  Polygon
4        27.361269  387955       0  Polygon
...            ...     ...     ...      ...
922820   86.413986  523519       0  Polygon
922821   19.730201  851199       0  Polygon
922822   27.102379  458239       0  Polygon
922823   74.472819  261887       0  Polygon
922824   30.037356  458751       0  Polygon

[922825 rows x 4 columns]

In [11]:
shapefile.damage.value_counts()

0    885373
1     37452
Name: damage, dtype: int64

In [27]:
# statistics of the area of the damaged buildings
shapefile[shapefile.damage == 1]['area'].describe()

count    37452.000000
mean       107.316953
std        184.704354
min          4.212493
25%         33.831551
50%         70.112924
75%        116.455040
max       5051.746966
Name: area, dtype: float64

In [28]:
shapefile[shapefile.damage == 0]['area'].describe()

count    885373.000000
mean         84.844385
std         181.784144
min           2.752644
25%          25.068649
50%          49.351815
75%          92.220631
max       19174.872277
Name: area, dtype: float64

In [26]:
# assuming sqrt function
shapefile[shapefile.damage == 1]['area'].apply(lambda x: damage_area_to_broken_windows(x)).sum()

339660.573316475