In [8]:
import geopandas as gpd
from simpledbf import Dbf5
from osgeo import gdal

import pandas as pd

from PIL import Image
import tifffile

import matplotlib.pyplot as plt

from shapely.geometry import Polygon

import folium

In [9]:
# SHP file
# SAMPLE
#shapefile = gpd.read_file("izium_building_damage_data_sample.shp") 

# FULL
shapefile = gpd.read_file("building_damage_data_eastern_cooridor_DAMAGED_ONLY.shp")


# DBF file. Contains all columns of .shp file except geometry
dbf = Dbf5('building_damage_data_eastern_cooridor_DAMAGED_ONLY.dbf')
polygons_without_geometry = dbf.to_dataframe()

# .fix file is not relevant

def damage_area_to_broken_windows(damage_area):
    """ 
    TODO: map damage area to broken windows using
     reasonable assumptions.
    """
    return damage_area**(1/2)

In [10]:
shapefile

,area,FID,damage,geoType,geometry
0,66.562067,695112,1,Polygon,"POLYGON ((33.42465 46.84461, 33.42473 46.84465..."
1,26.925033,910664,1,Polygon,"POLYGON ((33.43341 46.84777, 33.43345 46.84778..."
2,192.679681,312905,1,Polygon,"POLYGON ((33.42471 46.84412, 33.42489 46.84417..."
3,46.120026,296779,1,Polygon,"POLYGON ((33.42585 46.84267, 33.42601 46.84271..."
4,165.343184,646475,1,Polygon,"POLYGON ((33.42552 46.84268, 33.42570 46.84275..."
...,...,...,...,...,...
37447,95.008390,89070,1,Polygon,"POLYGON ((33.89652 51.69127, 33.89652 51.69134..."
37448,11.419012,893679,1,Polygon,"POLYGON ((33.93355 51.94945, 33.93361 51.94946..."
37449,16.812626,46834,1,Polygon,"POLYGON ((33.93480 51.94955, 33.93486 51.94957..."
37450,9.303976,998910,1,Polygon,"POLYGON ((33.93458 51.94904, 33.93461 51.94905..."
37451,17.549767,946942,1,Polygon,"POLYGON ((33.89631 51.69172, 33.89632 51.69176..."

In [11]:
polygons_without_geometry

             area     FID  damage  geoType
0       66.562067  695112       1  Polygon
1       26.925033  910664       1  Polygon
2      192.679681  312905       1  Polygon
3       46.120026  296779       1  Polygon
4      165.343184  646475       1  Polygon
...           ...     ...     ...      ...
37447   95.008390   89070       1  Polygon
37448   11.419012  893679       1  Polygon
37449   16.812626   46834       1  Polygon
37450    9.303976  998910       1  Polygon
37451   17.549767  946942       1  Polygon

[37452 rows x 4 columns]

In [12]:
shapefile.damage.value_counts()

1    37452
Name: damage, dtype: int64

In [13]:
# statistics of the area of the damaged buildings
shapefile[shapefile.damage == 1]['area'].describe()

count    37452.000000
mean       107.316953
std        184.704354
min          4.212493
25%         33.831551
50%         70.112924
75%        116.455040
max       5051.746966
Name: area, dtype: float64

In [14]:
# assuming sqrt function
shapefile[shapefile.damage == 1]['area'].apply(lambda x: damage_area_to_broken_windows(x)).sum()

339660.573316475